# Generated by Django 5.1.6 on 2025-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(editable=False, max_length=8, unique=True)),
                ("redirect_to", models.URLField()),
                (
                    "shortened_url",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
